name: linkurator

include:
  - backend/docker-compose.yml

services:
  postgres:
    profiles: !reset []
    environment:
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d main"]
      interval: 5s
      timeout: 5s
      retries: 10

  queue:
    profiles: !reset []
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    profiles: !reset []
    build:
      context: ./backend
    image: frantracer/linkurator-api
    volumes:
      - ./.config.json:/app/.config.json:ro
    depends_on:
      postgres:
        condition: service_healthy
      queue:
        condition: service_healthy

  processor:
    profiles: !reset []
    build:
      context: ./backend
    image: frantracer/linkurator-api
    volumes:
      - ./.config.json:/app/.config.json:ro
    depends_on:
      postgres:
        condition: service_healthy
      queue:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    image: frantracer/linkurator-frontend
    container_name: linkurator-frontend
    network_mode: host
    depends_on:
      - api

  generate-env:
    volumes:
      - ./:/output
