name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    env:
      DOCKER_PUBLISH_BRANCH: main
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Install Docker
        if: github.ref_name == env.DOCKER_PUBLISH_BRANCH
        uses: docker/setup-buildx-action@v4
      - name: Build image
        if: github.ref_name == env.DOCKER_PUBLISH_BRANCH
        run: docker build -t frantracer/linkurator-frontend .
      - name: Push image to Docker Hub
        if: github.ref_name == env.DOCKER_PUBLISH_BRANCH
        run: |
          docker login -u frantracer -p "$LINKURATOR_DOCKER_TOKEN"
          docker push frantracer/linkurator-frontend
        env:
          LINKURATOR_DOCKER_TOKEN: ${{secrets.LINKURATOR_DOCKER_TOKEN}}
